---
# handlers file for default/php
- name: restart nginx
  become: true
  service: name=nginx state=restarted enabled=yes
- name: restart php-fpm
  become: true
  service: name=php8.0-fpm state=restarted enabled=yes
