---
# tasks file for default/php
- name: Installs the ppa:ondrej/php repo on Ubuntu systems
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: "true"
- name: Install php
  become: true
  apt:
    name: ['php8.0', 'php8.0-mysql', 'php8.0-curl', 'php8.0-gd', 'php8.0-fpm', 'php8.0-mbstring', 'php8.0-xml', 'php8.0-dom']
- name: Set sendmail_path to sendmail -t -i
  become: true
  ini_file: dest=/etc/php/8.0/fpm/php.ini section=PHP option=sendmail_path value='sendmail -t -i'
  notify:
    - restart nginx
    - restart php-fpm
- name: Setting PHP error log path to /var/log/nginx/php_errors.log
  become: true
  ini_file: dest=/etc/php/8.0/fpm/php.ini section=PHP option=error_log value='/var/log/nginx/php_errors.log'
  notify:
    - restart nginx
    - restart php-fpm
- name: Ensure default www.conf is gone
  file: path=/etc/php/8.0/fpm/pool.d/www.conf state=absent
- name: Loading php-fpm configuration
  template: src=php-fpm-configuration.conf dest=/etc/php/8.0/fpm/pool.d/{{ projectname }}.conf
  notify:
    - restart nginx
    - restart php-fpm


