---
- hosts: all
  vars_files:
    - vars.yml
  become: true
#yes order is still important dont change it
  roles:
    - { role: default/default-tools, when: enable_default_tools  }
    - { role: default/nginx,         when: enable_nginx          }
    - { role: default/php,           when: enable_php            }
    - { role: default/php-dev,       when: enable_php_dev        }
    - { role: default/mariadb,       when: enable_mariadb        }
    - { role: default/composer,      when: enable_composer       }
